version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:16
    container_name: db   # đổi tên container để trùng với DB_HOST=db trong .env
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: thaoanhxinh
      POSTGRES_DB: warehouse_management
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  pgdata:
